mpc_follower:
  ros__parameters:
    # 时间参数
    Ts: 0.05 
    N: 30

    # 机器人物理约束
    MinR: 0.0
    MaxLinear: 2.0
    MinLinear: -2.0
    MaxAngular: 2.0
    MinAngular: -2.0

    # 加速度约束
    MaxAccelLinear: 1.5
    MinAccelLinear: -1.5
    MaxAccelAngular: 6.0
    MinAccelAngular: -6.0

      # MPC权重
    Wx: 20.0
    Wy: 20.0
    Wtheta: 10.0
    Wv: 0.02
    Womega: 0.1
    WRadius: 1.0
    kStopPenalty: 0.0
    Rv: 0.1
    Romega: 0.1

    # 优化器参数
    OptTolerance: 0.001
    GlobalMaxEval: 500
    LocalMaxEval: 1000
    GlobalInitNoise: 0.2

    # 障碍物参数
    ObstacleInflation: 0.5
    Wobs: 100.0
