goal_manager_node:
  ros__parameters:
    bias: 20
    r: [0.004, 0.146,   # R0: anti hero
        0.5604, 0.3857,   # R1: start
        -0.38455, -0.204,  # R2: self outpost
        4.90612, -2.09907,  # R3: circular highland patrol area
        0.185018, -5.49178]  # R4: supply area
        # 2.750, 4.467,   # R5: enemy outpost
        # 7.842, -15.43,  # R6: high land 2 patrol area
        # 1.005, -15.38,  # R7: supply area
        # -1.577, -12.7]  # R8: Big Buff
        
    b: [7.311, -3.032,  # B0: start
        0.5604, 0.3857,  # B1: self outpost
        -0.38455, -0.204,  # B2: circular highland patrol area
        4.90612, -2.09907,  # B3: high land 1 patrol area
        0.185018, -5.49178]   # B4: enemy outpost
        # 4.704, -1.913,  # B5: high land 2 patrol area
        # -0.319, -9.21,  # B6: supply area
        # 5.748, -8.817,  # B7: Big Buff
        # 8.639, -11.93]  # B8: anti hero